version: 2
project_name: eui64-calculator
before:
  hooks:
    - go mod download
    - go install github.com/a-h/templ/cmd/templ@latest
    - templ generate

builds:
  - main: ./cmd/server/main.go
    binary: eui64-calculator
    goos:
      - linux
    goarch:
      - amd64

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_v{{ .Version }}_
      {{ title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  github:
    owner: nicholas-fedor
    name: eui64-calculator
  draft: false
  prerelease: auto

dockers:
  - image_templates:
      - "docker.io/{{ .Env.DOCKERHUB_USERNAME }}/eui64-calculator:{{ .Tag }}"
      - "docker.io/{{ .Env.DOCKERHUB_USERNAME }}/eui64-calculator:{{ if .IsSnapshot }}latest-dev{{ else }}latest{{ end }}"
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY }}/eui64-calculator:{{ .Tag }}"
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY }}/eui64-calculator:{{ if .IsSnapshot }}latest-dev{{ else }}latest{{ end }}"
    dockerfile: docker/Dockerfile
    build_flag_templates:
      - "--platform=linux/amd64"
