---
#---------------------------------------------------------------------#
#                          EUI64-Calculator                           #
#---------------------------------------------------------------------#
name: eui64-calculator

networks:
  traefik:
    name: traefik
    internal: true

secrets:
  CLOUDFLARE_EMAIL:
    file: ./Traefik/Secrets/CLOUDFLARE_EMAIL
  CLOUDFLARE_DNS_API_TOKEN:
    file: ./Traefik/Secrets/CLOUDFLARE_DNS_API_TOKEN

services:
  eui64-calculator:
    container_name: eui64-calculator
    environment:
      - TRUSTED_PROXIES=${TRUSTED_PROXIES}
    image: nickfedor/eui64-calculator:latest@sha256:d8e5223cb46b6bfb83ce70e9264831f8b9e8560ef1faa06d2e7c1142c4640101
    labels:
      - traefik.enable=true
      - traefik.http.routers.eui64-calculator.rule=Host(`${DOMAIN_NAME}`)
      - traefik.http.routers.eui64-calculator.entrypoints=https
      - traefik.http.routers.eui64-calculator.service=eui64-calculator-svc
      - traefik.http.services.eui64-calculator-svc.loadbalancer.server.port=8080
      - traefik.http.routers.eui64-calculator.tls=true
      - traefik.http.routers.eui64-calculator.tls.certresolver=cloudflare
    networks:
      - traefik
    restart: unless-stopped

  traefik:
    container_name: traefik
    environment:
      - CLOUDFLARE_EMAIL_FILE=/run/secrets/CLOUDFLARE_EMAIL
      - CLOUDFLARE_DNS_API_TOKEN_FILE=/run/secrets/CLOUDFLARE_DNS_API_TOKEN
    image: traefik:latest@sha256:9b0e9d788816d722703eae57ebf8b4d52ad98e02b76f0362d5a040ef46902ef7
    restart: unless-stopped
    networks:
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.web.entrypoints=http
      - traefik.http.routers.web.rule=Host(`traefik.${DOMAIN_NAME}`)
      - traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https
      - traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https
      - traefik.http.routers.web.middlewares=traefik-https-redirect
      - traefik.http.routers.websecure.entrypoints=https
      - traefik.http.routers.websecure.rule=Host(`traefik.${DOMAIN_NAME}`)
      - traefik.http.routers.websecure.service=api@internal
      - traefik.http.routers.websecure.tls=true
      - traefik.http.routers.websecure.tls.certresolver=cloudflare
    ports:
      - 80:80
      - 443:443
    secrets:
      - CLOUDFLARE_EMAIL
      - CLOUDFLARE_DNS_API_TOKEN
    security_opt:
      - no-new-privileges:true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./Traefik/traefik.yaml:/etc/traefik/traefik.yaml:ro
      - ./Traefik/Certs/acme.json:/acme.json:rw
