name: Lint GitHub Actions workflows

on:
  workflow_dispatch: {}
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    paths:
      - .github/workflows/**

permissions:
  contents: read

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493

      - name: Download actionlint
        run: |
          curl -sSfL https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash | bash -s -- -b /usr/local/bin
          actionlint -version
        shell: bash

      - name: Check workflow files
        run: actionlint -color || exit 1
        shell: bash
