name: Pull Request

on:
  workflow_dispatch: {}
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  lint:
    uses: ./.github/workflows/lint.yaml@main

  test:
    uses: /.github/workflows/test.yaml@main

  build:
    uses: ./.github/workflows/build.yaml@main
