name: Release (Production)

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
  workflow_dispatch: {}

permissions:
  contents: write
  packages: write
  attestations: write

jobs:
  lint:
    uses: ./.github/workflows/lint.yaml

  test:
    uses: ./.github/workflows/test.yaml

  build:
    uses: ./.github/workflows/build.yaml@main
    needs:
      - test
      - lint

  renew-docs:
    name: Refresh pkg.go.dev
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Pull new module version
        uses: nicholas-fedor/go-proxy-pull-action@4678aed75a75576047e0bc4c15e10dd6eff95baf
        with:
          goproxy: https://proxy.golang.org
          import_path: github.com/nicholas-fedor/eui64-calculator
