name: Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  lint:
    name: Lint the project
    permissions:
      contents: read
    uses: ./.github/workflows/lint-go.yaml

  test:
    name: Run unit tests
    permissions:
      contents: read
    uses: ./.github/workflows/test.yaml

  build:
    name: Build the Release
    needs:
      - test
      - lint
    permissions:
      contents: write
      packages: write
      attestations: write
      id-token: write
    secrets: inherit
    uses: ./.github/workflows/build.yaml
    with:
      project_name: eui64-calculator
      docker_namespace: nickfedor
      ghcr_namespace: nicholas-fedor

  manifest:
    name: Create image manifests
    needs: build
    permissions:
      contents: read # For code checkout
      packages: write # For pushing manifests
      id-token: write
    secrets: inherit
    uses: ./.github/workflows/create-manifests.yaml
    with:
      version: ${{ github.ref_name }} # Tag name (e.g., v1.2.3)
      project_name: eui64-calculator
      docker_namespace: nickfedor
      ghcr_namespace: nicholas-fedor

  deploy-gh-pages:
    name: Deploy to GitHub Pages
    needs:
      - test
      - lint
    permissions:
      contents: write
    secrets: inherit
    uses: ./.github/workflows/deploy-gh-pages.yaml

  Update-Go-Docs:
    name: Update Go docs
    needs:
      - lint
      - test
      - build
      - manifest
    permissions:
      contents: read
    uses: ./.github/workflows/update-go-docs.yaml
