name: Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

permissions:
  contents: read

jobs:
  # Run Go tests and upload coverage
  test:
    uses: ./.github/workflows/test.yaml

  # Build binaries, images, SBOMs, and attestations
  build:
    needs: [test] # Requires tests to pass
    uses: ./.github/workflows/build.yaml
    with:
      project_name: eui64-calculator
      docker_namespace: nickfedor
      ghcr_namespace: nicholas-fedor
      environment: CI

  deploy-gh-pages:
    name: Deploy to GitHub Pages
    needs:
      - test
    uses: ./.github/workflows/deploy-gh-pages.yaml

  Update-Go-Docs:
    name: Update Go docs
    needs:
      - test
      - build
    uses: ./.github/workflows/update-go-docs.yaml
