name: Push to main

on:
  workflow_dispatch: {}
  push:
    branches:
      - main

permissions:
  contents: write
  actions: read
  packages: write
  id-token: write
  attestations: write

jobs:
  lint:
    uses: ./.github/workflows/lint.yaml

  test:
    uses: ./.github/workflows/test.yaml

  build-and-publish:
    uses: ./.github/workflows/build.yaml
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    needs:
      - test
      - lint
    with:
      snapshot: true
